server:
  port: 8080

spring:
  application:
    name: LoanWisely

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: C##PROTOV1
    password: PROTOV1

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    # schemas는 환경에 맞게 필요 시만 사용
    # schemas: C##SECUREAPI

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.ccksy.loan
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.ccksy.loan: DEBUG
    org.mybatis: DEBUG
