spring:
  application:
    name: loan-wisely

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: C##KH
    password: KH

mybatis:
  configuration:
    map-underscore-to-camel-case: true
