-- RAW_FILE_ROW (staging rows for ingestion)
CREATE TABLE RAW_FILE_ROW (
    row_id     NUMBER       NOT NULL,
    upload_id  NUMBER       NOT NULL,
    row_num    NUMBER       NOT NULL,
    row_json   CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_ROW PRIMARY KEY (row_id)
);

CREATE SEQUENCE RAW_FILE_ROW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_RAW_FILE_ROW_UPLOAD ON RAW_FILE_ROW (upload_id, row_num);

-- APPROVAL_LOG (approval actions with reason)
CREATE TABLE APPROVAL_LOG (
    approval_id NUMBER       NOT NULL,
    target_id   VARCHAR2(200) NOT NULL,
    action      VARCHAR2(20)  NOT NULL,
    reason      VARCHAR2(1000),
    actor_id    VARCHAR2(100),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APPROVAL_LOG PRIMARY KEY (approval_id)
);

CREATE SEQUENCE APPROVAL_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_APPROVAL_LOG_TARGET ON APPROVAL_LOG (target_id, created_at DESC);
