-- USER_CREDIT_LV1 append-only
ALTER TABLE USER_CREDIT_LV1 ADD (
    lv1_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV1_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV1 SET lv1_id = USER_CREDIT_LV1_SEQ.NEXTVAL, is_active = 'Y' WHERE lv1_id IS NULL;
ALTER TABLE USER_CREDIT_LV1 MODIFY lv1_id NOT NULL;
ALTER TABLE USER_CREDIT_LV1 DROP CONSTRAINT PK_USER_CREDIT_LV1;
ALTER TABLE USER_CREDIT_LV1 ADD CONSTRAINT PK_USER_CREDIT_LV1 PRIMARY KEY (lv1_id);
CREATE INDEX IDX_UCLV1_USER_ACTIVE ON USER_CREDIT_LV1 (user_id, is_active, created_at DESC);

-- USER_CREDIT_LV2 append-only
ALTER TABLE USER_CREDIT_LV2 ADD (
    lv2_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV2_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV2 SET lv2_id = USER_CREDIT_LV2_SEQ.NEXTVAL, is_active = 'Y' WHERE lv2_id IS NULL;
ALTER TABLE USER_CREDIT_LV2 MODIFY lv2_id NOT NULL;
ALTER TABLE USER_CREDIT_LV2 DROP CONSTRAINT PK_USER_CREDIT_LV2;
ALTER TABLE USER_CREDIT_LV2 ADD CONSTRAINT PK_USER_CREDIT_LV2 PRIMARY KEY (lv2_id);
CREATE INDEX IDX_UCLV2_USER_ACTIVE ON USER_CREDIT_LV2 (user_id, is_active, created_at DESC);

-- USER_CREDIT_LV3 append-only
ALTER TABLE USER_CREDIT_LV3 ADD (
    lv3_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV3_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV3 SET lv3_id = USER_CREDIT_LV3_SEQ.NEXTVAL, is_active = 'Y' WHERE lv3_id IS NULL;
ALTER TABLE USER_CREDIT_LV3 MODIFY lv3_id NOT NULL;
ALTER TABLE USER_CREDIT_LV3 DROP CONSTRAINT PK_USER_CREDIT_LV3;
ALTER TABLE USER_CREDIT_LV3 ADD CONSTRAINT PK_USER_CREDIT_LV3 PRIMARY KEY (lv3_id);
CREATE INDEX IDX_UCLV3_USER_ACTIVE ON USER_CREDIT_LV3 (user_id, is_active, created_at DESC);
