-- PROVIDER_URL: 금융사 홈페이지 URL 매핑
CREATE TABLE PROVIDER_URL (
    fin_co_no     VARCHAR2(20) PRIMARY KEY,
    homepage_url  VARCHAR2(500) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_PROVIDER_URL_HOME ON PROVIDER_URL (homepage_url);
