-- RAW_FILE_UPLOAD (Admin raw file pipeline)
CREATE TABLE RAW_FILE_UPLOAD (
    upload_id    NUMBER       NOT NULL,
    file_name    VARCHAR2(400) NOT NULL,
    file_hash    VARCHAR2(200),
    uploader_id  NUMBER,
    stored_path  VARCHAR2(1000),
    status       VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
    uploaded_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_UPLOAD PRIMARY KEY (upload_id)
);

CREATE SEQUENCE RAW_FILE_UPLOAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_RAW_FILE_UPLOAD_STATUS ON RAW_FILE_UPLOAD (status, uploaded_at DESC);
