-- FINANCIAL_META_VERSION
CREATE TABLE FINANCIAL_META_VERSION (
    version_id    NUMBER       NOT NULL,
    version_label VARCHAR2(200),
    meta_json     CLOB,
    status        VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at   TIMESTAMP,
    approved_by   VARCHAR2(100),
    is_active     CHAR(1) DEFAULT 'N' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FINANCIAL_META_VERSION PRIMARY KEY (version_id)
);

CREATE SEQUENCE FINANCIAL_META_VERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_ACTIVE
    CHECK (is_active IN ('Y','N'));

CREATE INDEX IDX_FIN_META_ACTIVE ON FINANCIAL_META_VERSION (is_active, status, approved_at DESC);

-- AUDIT_LOG (Admin audit)
CREATE TABLE AUDIT_LOG (
    audit_id   NUMBER       NOT NULL,
    actor_id   VARCHAR2(100),
    action     VARCHAR2(50),
    target     VARCHAR2(200),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (audit_id)
);

CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_AUDIT_LOG_CREATED ON AUDIT_LOG (created_at DESC);
