-- Extend status enums to include REJECTED

ALTER TABLE CODE_DICTIONARY_VERSION DROP CONSTRAINT CK_CODE_DICT_STATUS;
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));

ALTER TABLE RECO_POLICY DROP CONSTRAINT CK_RECO_POLICY_STATUS;
ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));

ALTER TABLE FINANCIAL_META_VERSION DROP CONSTRAINT CK_FIN_META_STATUS;
ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));
