CREATE TABLE USER_AUTH (
    user_id       NUMBER       NOT NULL,
    username      VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT PK_USER_AUTH PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_AUTH_USERNAME UNIQUE (username)
);

CREATE SEQUENCE USER_AUTH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
