-- =========================================================
-- V1: 기반/루트 (CATEGORY_*, USER_*, RAW_FILE_UPLOAD)
-- =========================================================

-- 44) CATEGORY_SET
CREATE TABLE CATEGORY_SET (
  category_set_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_set_key    VARCHAR2(100) NOT NULL,
  category_set_name   VARCHAR2(200) NOT NULL,
  description         VARCHAR2(1000),
  is_active           CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_CATEGORY_SET_ACTIVE CHECK (is_active IN ('Y','N'))
);

CREATE UNIQUE INDEX UX_CATEGORY_SET_KEY ON CATEGORY_SET(category_set_key);

-- 45) CATEGORY_VALUE
CREATE TABLE CATEGORY_VALUE (
  category_value_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_set_id     NUMBER NOT NULL,
  code                VARCHAR2(100) NOT NULL,
  category_name       VARCHAR2(200) NOT NULL,
  sort_order          NUMBER,
  is_active           CHAR(1) DEFAULT 'Y' NOT NULL,
  effective_from      TIMESTAMP,
  effective_to        TIMESTAMP,
  created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_CATEGORY_VALUE_ACTIVE CHECK (is_active IN ('Y','N')),
  CONSTRAINT CK_CATEGORY_VALUE_EFFECTIVE CHECK (
    effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to
  )
);

-- (category_set_id, code)로 유니크는 아주 좋습니다.
CREATE UNIQUE INDEX UX_CATEGORY_VALUE_CODE ON CATEGORY_VALUE(category_set_id, code);

ALTER TABLE CATEGORY_VALUE
  ADD CONSTRAINT FK_CATVAL_SET
  FOREIGN KEY (category_set_id) REFERENCES CATEGORY_SET(category_set_id);

-- FK 컬럼은 조인/검증에 자주 쓰이므로 인덱스 권장 (성능 + 잠금 이슈 완화)
CREATE INDEX IX_CATEGORY_VALUE_SET ON CATEGORY_VALUE(category_set_id);

-- 13) USER_PROFILE
CREATE TABLE USER_PROFILE (
  user_id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  principal_type_category_value_id NUMBER NOT NULL, -- SESSION/ADMIN/CUSTOMER (CATEGORY_VALUE 참조)
  created_at                       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_PROFILE
  ADD CONSTRAINT FK_USER_PROFILE_PRINCIPAL_TYPE
  FOREIGN KEY (principal_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장
CREATE INDEX IX_USER_PROFILE_PRINCIPAL_TYPE ON USER_PROFILE(principal_type_category_value_id);

-- 15) CUSTOMER_PROFILE
CREATE TABLE CUSTOMER_PROFILE (
  user_id      NUMBER PRIMARY KEY,
  user_name    VARCHAR2(200),
  phone        VARCHAR2(50),
  email        VARCHAR2(200)
);

ALTER TABLE CUSTOMER_PROFILE
  ADD CONSTRAINT FK_CUSTOMER_PROFILE_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

-- 16) SESSION_PROFILE
CREATE TABLE SESSION_PROFILE (
  user_id       NUMBER PRIMARY KEY,
  session_key   VARCHAR2(200) NOT NULL,
  expires_at    TIMESTAMP,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 세션키는 보통 유니크가 안전합니다(동일 세션키 중복 방지)
CREATE UNIQUE INDEX UX_SESSION_PROFILE_KEY ON SESSION_PROFILE(session_key);

ALTER TABLE SESSION_PROFILE
  ADD CONSTRAINT FK_SESSION_PROFILE_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

-- 17) ADMIN_PROFILE
CREATE TABLE ADMIN_PROFILE (
  user_id     NUMBER PRIMARY KEY,
  admin_name  VARCHAR2(200)
);

ALTER TABLE ADMIN_PROFILE
  ADD CONSTRAINT FK_ADMIN_PROFILE_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

-- 14) USER_ACCOUNT (로그인 기능이 확정이 아니라면 제거 가능)
-- ※ FK 관점에서 문제는 없지만, "유저 1명당 계정 1개"라면 (user_id) 유니크가 보통 안전합니다.
CREATE TABLE USER_ACCOUNT (
  account_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           NUMBER NOT NULL,
  login_id          VARCHAR2(200) NOT NULL,
  password_hash     VARCHAR2(500) NOT NULL,
  last_login_at     TIMESTAMP,
  is_locked         CHAR(1) DEFAULT 'N' NOT NULL,
  fail_login_count  NUMBER DEFAULT 0 NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_USER_ACCOUNT_LOCKED CHECK (is_locked IN ('Y','N')),
  CONSTRAINT CK_USER_ACCOUNT_FAIL_COUNT CHECK (fail_login_count >= 0)
);

CREATE UNIQUE INDEX UX_USER_ACCOUNT_LOGIN ON USER_ACCOUNT(login_id);

-- (선택) 유저당 계정 1개 정책이면 아래 유니크 인덱스 권장
CREATE UNIQUE INDEX UX_USER_ACCOUNT_USER ON USER_ACCOUNT(user_id);

ALTER TABLE USER_ACCOUNT
  ADD CONSTRAINT FK_USER_ACCOUNT_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

-- 1) RAW_FILE_UPLOAD
CREATE TABLE RAW_FILE_UPLOAD (
  upload_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name                VARCHAR2(500) NOT NULL,
  file_hash                VARCHAR2(200),
  uploader_id              NUMBER NOT NULL, -- ADMIN/업로더
  uploaded_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status_category_value_id NUMBER NOT NULL
);

ALTER TABLE RAW_FILE_UPLOAD
  ADD CONSTRAINT FK_RAW_FILE_UPLOAD_UPLOADER
  FOREIGN KEY (uploader_id) REFERENCES USER_PROFILE(user_id);

ALTER TABLE RAW_FILE_UPLOAD
  ADD CONSTRAINT FK_RAW_FILE_UPLOAD_STATUS
  FOREIGN KEY (status_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장 (대용량 업로드/조회 시 성능 + 락 완화)
CREATE INDEX IX_RAW_FILE_UPLOAD_UPLOADER ON RAW_FILE_UPLOAD(uploader_id);
CREATE INDEX IX_RAW_FILE_UPLOAD_STATUS   ON RAW_FILE_UPLOAD(status_category_value_id);
