-- Consolidated Flyway migration for NEW database bootstrap only
-- Generated by consolidating legacy migrations V1~V23
-- IMPORTANT: Do not use this consolidated set against an existing DB with Flyway history.
-- Legacy migrations were moved to: db/migration_legacy_20260224_102506

-- ===== BEGIN V1__create_user_profile.sql =====
-- USER_PROFILE: 사용자 입력/이력 (이력 불변 + 활성 플래그)
-- 정책:
-- - 같은 user_id에 대해 최신 유효 1건만 is_active='Y'
-- - 신규 입력 시 기존 is_active='Y'를 'N'으로 바꾸고 신규 row insert

CREATE TABLE USER_PROFILE (
    profile_id           NUMBER          NOT NULL,
    user_id              NUMBER          NOT NULL,
    input_level          NUMBER          NOT NULL,

    age                  NUMBER,
    income_year          NUMBER,
    gender               VARCHAR2(20),

    employment_type      VARCHAR2(50),
    residence_type       VARCHAR2(50),

    debt_total           NUMBER,
    existing_loan_count  NUMBER,
    loan_purpose         VARCHAR2(100),

    input_state_code     VARCHAR2(50),
    is_active            CHAR(1)         DEFAULT 'Y' NOT NULL,
    created_at           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_USER_PROFILE PRIMARY KEY (profile_id),
    CONSTRAINT CK_USER_PROFILE_ACTIVE CHECK (is_active IN ('Y','N')),
    CONSTRAINT CK_USER_PROFILE_LEVEL CHECK (input_level IN (1,2,3))
);

-- PK 시퀀스
CREATE SEQUENCE USER_PROFILE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 조회 성능: 최신 유효 조회/이력 조회 지원
CREATE INDEX IDX_USER_PROFILE_USER_ACTIVE
    ON USER_PROFILE (user_id, is_active, created_at DESC);

CREATE INDEX IDX_USER_PROFILE_USER_CREATED
    ON USER_PROFILE (user_id, created_at DESC);
-- ===== END V1__create_user_profile.sql =====

-- ===== BEGIN V2__create_loan_product.sql =====
-- LOAN_PRODUCT: 대출상품(기본정보)
-- 정책:
-- - product_id는 시퀀스로 생성
-- - CODE_VALUE 기반 코드 컬럼은 code_value_id 문자열로 보관(v1)

CREATE TABLE LOAN_PRODUCT (
    product_id                   NUMBER           NOT NULL,
    provider_id                  NUMBER           NOT NULL,

    product_name                 VARCHAR2(200)    NOT NULL,

    product_type_code_value_id   VARCHAR2(50)     NOT NULL,
    loan_type_code_value_id      VARCHAR2(50)     NOT NULL,
    repayment_type_code_value_id VARCHAR2(50)     NOT NULL,

    collateral_type_code_value_id VARCHAR2(50),
    rate_type_code_value_id      VARCHAR2(50),

    note                         VARCHAR2(1000),

    add_date                     TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    end_date                     DATE,
    updated_at                   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_LOAN_PRODUCT PRIMARY KEY (product_id)
);

-- PK 시퀀스
CREATE SEQUENCE LOAN_PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 조회/정렬 성능
CREATE INDEX IDX_LOAN_PRODUCT_PROVIDER
    ON LOAN_PRODUCT (provider_id);

CREATE INDEX IDX_LOAN_PRODUCT_UPDATED
    ON LOAN_PRODUCT (updated_at DESC, add_date DESC);
-- ===== END V2__create_loan_product.sql =====

-- ===== BEGIN V3__create_user_consent.sql =====
-- USER_CONSENT: 사용자 LV별 동의 이력 (이력 불변 + 활성 플래그)
-- 정책:
-- - 같은 (user_id, consent_level) 조합에 대해 최신 유효 1건만 is_active='Y'
-- - 신규 입력 시 기존 is_active='Y'를 'N'으로 바꾸고 신규 row insert

CREATE TABLE USER_CONSENT (
    consent_id      NUMBER          NOT NULL,
    user_id         NUMBER          NOT NULL,
    consent_level   NUMBER          NOT NULL,  -- 1~3 (LV)
    consent_given   CHAR(1)         NOT NULL,  -- 'Y'/'N'
    is_active       CHAR(1)         DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_USER_CONSENT PRIMARY KEY (consent_id),
    CONSTRAINT CK_USER_CONSENT_LEVEL CHECK (consent_level IN (1,2,3)),
    CONSTRAINT CK_USER_CONSENT_GIVEN CHECK (consent_given IN ('Y','N')),
    CONSTRAINT CK_USER_CONSENT_ACTIVE CHECK (is_active IN ('Y','N'))
);

-- PK 시퀀스
CREATE SEQUENCE USER_CONSENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 조회 성능: 최신 유효 조회 / 이력 조회
CREATE INDEX IDX_USER_CONSENT_USER_LEVEL_ACTIVE
    ON USER_CONSENT (user_id, consent_level, is_active, created_at DESC);

CREATE INDEX IDX_USER_CONSENT_USER_LEVEL_CREATED
    ON USER_CONSENT (user_id, consent_level, created_at DESC);
-- ===== END V3__create_user_consent.sql =====

-- ===== BEGIN V4__create_recommend_history.sql =====
-- RECOMMEND_HISTORY: 추천 이력(재현/감사/증거 경로 포함)
-- 정책:
-- - DB에는 JSON 자체 저장하지 않음 (경로만 저장)
-- - reproduce_key는 재현 키이므로 UNIQUE
-- - append-only 성격(삭제/갱신 최소화). v1에서는 update 사용하지 않음

CREATE TABLE RECOMMEND_HISTORY (
    recommend_id         NUMBER           NOT NULL,
    user_id              NUMBER           NOT NULL,

    reproduce_key        VARCHAR2(200)    NOT NULL,

    recommend_state      VARCHAR2(30)     NOT NULL,  -- READY / NOT_READY / BLOCKED

    policy_version       VARCHAR2(100),
    meta_version         VARCHAR2(100),

    evidence_file_path   VARCHAR2(1000),
    explain_file_path    VARCHAR2(1000),

    created_at           TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_RECOMMEND_HISTORY PRIMARY KEY (recommend_id),
    CONSTRAINT UQ_RECOMMEND_HISTORY_REPRODUCE UNIQUE (reproduce_key)
);

-- PK 시퀀스
CREATE SEQUENCE RECOMMEND_HISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 조회 성능
CREATE INDEX IDX_RECOMMEND_HISTORY_USER
    ON RECOMMEND_HISTORY (user_id, created_at DESC);

CREATE INDEX IDX_RECOMMEND_HISTORY_STATE
    ON RECOMMEND_HISTORY (recommend_state, created_at DESC);
-- ===== END V4__create_recommend_history.sql =====

-- ===== BEGIN V5__create_core_erd.sql =====
-- 설계서 기준 ERD 핵심 테이블 (정식 마이그레이션)
-- 출처: `5. ERD.pdf`
-- 주의: 컬럼/자료형/제약은 ERD 상세 기준으로 추가 보정 필요
-- 대상 DB: Oracle (NUMBER, VARCHAR2, TIMESTAMP, DATE)

-- =====================================================
-- USER CREDIT (LV1/2/3)
-- =====================================================
CREATE TABLE USER_CREDIT_LV1 (
    user_id        NUMBER    NOT NULL, -- PK, FK -> USER_PROFILE.user_id
    age            NUMBER,
    income_year    NUMBER,
    gender         VARCHAR2(20),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_CREDIT_LV1 PRIMARY KEY (user_id)
);

CREATE TABLE USER_CREDIT_LV2 (
    user_id          NUMBER    NOT NULL, -- PK, FK -> USER_PROFILE.user_id
    employment_type  VARCHAR2(50),
    residence_type   VARCHAR2(50),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_CREDIT_LV2 PRIMARY KEY (user_id)
);

CREATE TABLE USER_CREDIT_LV3 (
    user_id              NUMBER    NOT NULL, -- PK, FK -> USER_PROFILE.user_id
    loan_purpose         VARCHAR2(100),
    total_debt           NUMBER,
    existing_loan_count  NUMBER,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_CREDIT_LV3 PRIMARY KEY (user_id)
);

-- =====================================================
-- CODE DICTIONARY (메타데이터)
-- =====================================================
CREATE TABLE CODE_DICTIONARY_VERSION (
    version_id      NUMBER       NOT NULL,
    upload_id       NUMBER,       -- FK -> RAW_FILE_UPLOAD.upload_id
    version_label   VARCHAR2(200),
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CODE_DICT_VERSION PRIMARY KEY (version_id)
);

CREATE TABLE CODE_DICTIONARY (
    dict_id            NUMBER       NOT NULL,
    version_id         NUMBER       NOT NULL, -- FK -> CODE_DICTIONARY_VERSION.version_id
    column_code        VARCHAR2(200),
    column_name        VARCHAR2(200),
    column_desc        VARCHAR2(1000),
    large_category_code_value_id  VARCHAR2(100),
    mideum_category_code_value_id VARCHAR2(100),
    small_category_code_value_id  VARCHAR2(100),
    is_required        CHAR(1),
    data_type          VARCHAR2(50),
    created_at         TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CODE_DICTIONARY PRIMARY KEY (dict_id)
);

CREATE TABLE CODE_DICTIONARY_DIFF (
    diff_id          NUMBER       NOT NULL,
    pre_version_id   NUMBER       NOT NULL, -- FK -> CODE_DICTIONARY_VERSION.version_id
    post_version_id  NUMBER       NOT NULL, -- FK -> CODE_DICTIONARY_VERSION.version_id
    change_type      VARCHAR2(20),
    column_code      VARCHAR2(200),
    before_json_path VARCHAR2(1000),
    after_json_path  VARCHAR2(1000),
    created_at       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CODE_DICTIONARY_DIFF PRIMARY KEY (diff_id)
);

-- =====================================================
-- RECOMMENDATION CORE
-- =====================================================
CREATE TABLE RECO_POLICY (
    policy_id                NUMBER       NOT NULL,
    version                  VARCHAR2(100),
    policy_type_code_value_id VARCHAR2(100),
    policy_key               VARCHAR2(200),
    policy_value             VARCHAR2(2000),
    effective_from           TIMESTAMP,
    effective_to             TIMESTAMP,
    created_at               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_POLICY PRIMARY KEY (policy_id)
);

CREATE TABLE RECO_REQUEST (
    request_id     NUMBER       NOT NULL,
    user_id        NUMBER       NOT NULL, -- FK -> USER_PROFILE.user_id
    version_id     NUMBER,       -- FK -> CODE_DICTIONARY_VERSION.version_id
    requested_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_REQUEST PRIMARY KEY (request_id)
);

CREATE TABLE RECO_RESULT (
    result_id               NUMBER       NOT NULL,
    request_id              NUMBER       NOT NULL, -- FK -> RECO_REQUEST.request_id
    overall_score           NUMBER,
    policy_version          VARCHAR2(100),
    confidence_level_code_value_id VARCHAR2(100),
    explanation_json_path   VARCHAR2(1000),
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_RESULT PRIMARY KEY (result_id)
);

CREATE TABLE RECO_ITEM (
    item_id          NUMBER       NOT NULL,
    result_id        NUMBER       NOT NULL, -- FK -> RECO_RESULT.result_id
    product_id       NUMBER       NOT NULL, -- FK -> LOAN_PRODUCT.product_id
    matching_score   NUMBER,
    estimated_rate   NUMBER,
    estimated_limit  NUMBER,
    stability_score  NUMBER,
    reason_json_path VARCHAR2(1000),
    rank             NUMBER,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_ITEM PRIMARY KEY (item_id)
);

CREATE TABLE RECO_ESTIMATION_DETAIL (
    detail_id      NUMBER       NOT NULL,
    snapshot_id    NUMBER,       -- FK -> USER_CREDIT_SNAPSHOT.snapshot_id (선택)
    item_id        NUMBER       NOT NULL, -- FK -> RECO_ITEM.item_id
    factor_code    VARCHAR2(100),
    factor_name    VARCHAR2(200),
    factor_value   VARCHAR2(1000),
    contribution   NUMBER,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_ESTIMATION_DETAIL PRIMARY KEY (detail_id)
);

CREATE TABLE RECO_EXCLUSION_REASON (
    reason_id    NUMBER       NOT NULL,
    result_id    NUMBER       NOT NULL, -- FK -> RECO_RESULT.result_id
    product_id   NUMBER       NOT NULL, -- FK -> LOAN_PRODUCT.product_id
    reason_code  VARCHAR2(100),
    reason_text  VARCHAR2(1000),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_EXCLUSION_REASON PRIMARY KEY (reason_id)
);

CREATE TABLE RECO_REJECT_LOG (
    reject_id     NUMBER       NOT NULL,
    request_id    NUMBER       NOT NULL, -- FK -> RECO_REQUEST.request_id
    product_id    NUMBER       NOT NULL, -- FK -> LOAN_PRODUCT.product_id
    reject_code   VARCHAR2(100),
    reject_reason VARCHAR2(1000),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECO_REJECT_LOG PRIMARY KEY (reject_id)
);

CREATE TABLE RECO_EVENT_LOG (
    log_id      NUMBER       NOT NULL,
    masked_user_id VARCHAR2(200),
    product_id  NUMBER,       -- FK -> LOAN_PRODUCT.product_id
    event_type_code_value_id VARCHAR2(100),
    occurred_at TIMESTAMP,
    CONSTRAINT PK_RECO_EVENT_LOG PRIMARY KEY (log_id)
);

-- =====================================================
-- FK 제약 (ERD 확정 후 구체화)
-- =====================================================
-- 주의: 아래 FK는 참조 테이블/컬럼 확정 시 활성화 권장
-- 예시)
-- ALTER TABLE USER_CREDIT_LV1
--   ADD CONSTRAINT FK_UCLV1_USER
--   FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);
--
-- ALTER TABLE RECO_ITEM
--   ADD CONSTRAINT FK_RECO_ITEM_PRODUCT
--   FOREIGN KEY (product_id) REFERENCES LOAN_PRODUCT(product_id);
--
-- ALTER TABLE RECO_REQUEST
--   ADD CONSTRAINT FK_RECO_REQ_USER
--   FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);
--
-- ALTER TABLE RECO_RESULT
--   ADD CONSTRAINT FK_RECO_RESULT_REQ
--   FOREIGN KEY (request_id) REFERENCES RECO_REQUEST(request_id);

-- =====================================================
-- 인덱스 (조회 패턴 기준, 필요 시 조정)
-- =====================================================
CREATE INDEX IDX_UCLV1_CREATED ON USER_CREDIT_LV1 (created_at DESC);
CREATE INDEX IDX_UCLV2_CREATED ON USER_CREDIT_LV2 (created_at DESC);
CREATE INDEX IDX_UCLV3_CREATED ON USER_CREDIT_LV3 (created_at DESC);

CREATE INDEX IDX_RECO_REQUEST_USER ON RECO_REQUEST (user_id, requested_at DESC);
CREATE INDEX IDX_RECO_RESULT_REQ ON RECO_RESULT (request_id, created_at DESC);
CREATE INDEX IDX_RECO_ITEM_RESULT ON RECO_ITEM (result_id, rank);
CREATE INDEX IDX_RECO_EXCLUSION_RESULT ON RECO_EXCLUSION_REASON (result_id, created_at DESC);
CREATE INDEX IDX_RECO_REJECT_REQ ON RECO_REJECT_LOG (request_id, created_at DESC);

CREATE INDEX IDX_CODE_DICT_VERSION ON CODE_DICTIONARY (version_id);
CREATE INDEX IDX_CODE_DICT_DIFF_VER ON CODE_DICTIONARY_DIFF (pre_version_id, post_version_id);

-- =====================================================
-- 시퀀스 (Oracle)
-- =====================================================
CREATE SEQUENCE CODE_DICTIONARY_VERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CODE_DICTIONARY_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CODE_DICTIONARY_DIFF_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE RECO_POLICY_SEQ            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_REQUEST_SEQ           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_RESULT_SEQ            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_ITEM_SEQ              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_ESTIMATION_DETAIL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_EXCLUSION_REASON_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_REJECT_LOG_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECO_EVENT_LOG_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =====================================================
-- TODO (한국어 기준)
-- - USER_PROFILE/LOAN_PRODUCT/USER_CREDIT_SNAPSHOT 확정 후 FK 제약 추가
-- - ERD 기준 컬럼명/자료형 정합성 재검증
-- - 인덱스는 실제 조회 패턴에 따라 추가/삭제
-- - PK 생성 방식(시퀀스/트리거/애플리케이션) 최종 결정
-- =====================================================
-- ===== END V5__create_core_erd.sql =====

-- ===== BEGIN V6__add_approval_fields.sql =====
-- 승인/활성 버전 컬럼 추가 (CODE_DICTIONARY_VERSION, RECO_POLICY)
-- 설계서 기준 승인/활성 분리 적용

ALTER TABLE CODE_DICTIONARY_VERSION ADD (
    status      VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR2(100),
    is_active   CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE RECO_POLICY ADD (
    status      VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR2(100),
    is_active   CHAR(1) DEFAULT 'N' NOT NULL
);

-- 상태 체크 제약
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

-- 활성 플래그 체크 제약
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_ACTIVE
    CHECK (is_active IN ('Y','N'));

ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_ACTIVE
    CHECK (is_active IN ('Y','N'));

-- 조회 인덱스
CREATE INDEX IDX_CODE_DICT_ACTIVE ON CODE_DICTIONARY_VERSION (is_active, status, approved_at DESC);
CREATE INDEX IDX_RECO_POLICY_ACTIVE ON RECO_POLICY (is_active, status, approved_at DESC);
-- ===== END V6__add_approval_fields.sql =====

-- ===== BEGIN V7__create_admin_raw_files.sql =====
-- RAW_FILE_UPLOAD (Admin raw file pipeline)
CREATE TABLE RAW_FILE_UPLOAD (
    upload_id    NUMBER       NOT NULL,
    file_name    VARCHAR2(400) NOT NULL,
    file_hash    VARCHAR2(200),
    uploader_id  NUMBER,
    stored_path  VARCHAR2(1000),
    status       VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
    uploaded_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_UPLOAD PRIMARY KEY (upload_id)
);

CREATE SEQUENCE RAW_FILE_UPLOAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_RAW_FILE_UPLOAD_STATUS ON RAW_FILE_UPLOAD (status, uploaded_at DESC);
-- ===== END V7__create_admin_raw_files.sql =====

-- ===== BEGIN V8__create_financial_meta_and_audit.sql =====
-- FINANCIAL_META_VERSION
CREATE TABLE FINANCIAL_META_VERSION (
    version_id    NUMBER       NOT NULL,
    version_label VARCHAR2(200),
    meta_json     CLOB,
    status        VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at   TIMESTAMP,
    approved_by   VARCHAR2(100),
    is_active     CHAR(1) DEFAULT 'N' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FINANCIAL_META_VERSION PRIMARY KEY (version_id)
);

CREATE SEQUENCE FINANCIAL_META_VERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_ACTIVE
    CHECK (is_active IN ('Y','N'));

CREATE INDEX IDX_FIN_META_ACTIVE ON FINANCIAL_META_VERSION (is_active, status, approved_at DESC);

-- AUDIT_LOG (Admin audit)
CREATE TABLE AUDIT_LOG (
    audit_id   NUMBER       NOT NULL,
    actor_id   VARCHAR2(100),
    action     VARCHAR2(50),
    target     VARCHAR2(200),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (audit_id)
);

CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_AUDIT_LOG_CREATED ON AUDIT_LOG (created_at DESC);
-- ===== END V8__create_financial_meta_and_audit.sql =====

-- ===== BEGIN V9__extend_status_enums.sql =====
-- Extend status enums to include REJECTED

ALTER TABLE CODE_DICTIONARY_VERSION DROP CONSTRAINT CK_CODE_DICT_STATUS;
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));

ALTER TABLE RECO_POLICY DROP CONSTRAINT CK_RECO_POLICY_STATUS;
ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));

ALTER TABLE FINANCIAL_META_VERSION DROP CONSTRAINT CK_FIN_META_STATUS;
ALTER TABLE FINANCIAL_META_VERSION ADD CONSTRAINT CK_FIN_META_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED','REJECTED'));
-- ===== END V9__extend_status_enums.sql =====

-- ===== BEGIN V10__raw_file_stage_and_approval_log.sql =====
-- RAW_FILE_ROW (staging rows for ingestion)
CREATE TABLE RAW_FILE_ROW (
    row_id     NUMBER       NOT NULL,
    upload_id  NUMBER       NOT NULL,
    row_num    NUMBER       NOT NULL,
    row_json   CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_ROW PRIMARY KEY (row_id)
);

CREATE SEQUENCE RAW_FILE_ROW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_RAW_FILE_ROW_UPLOAD ON RAW_FILE_ROW (upload_id, row_num);

-- APPROVAL_LOG (approval actions with reason)
CREATE TABLE APPROVAL_LOG (
    approval_id NUMBER       NOT NULL,
    target_id   VARCHAR2(200) NOT NULL,
    action      VARCHAR2(20)  NOT NULL,
    reason      VARCHAR2(1000),
    actor_id    VARCHAR2(100),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APPROVAL_LOG PRIMARY KEY (approval_id)
);

CREATE SEQUENCE APPROVAL_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_APPROVAL_LOG_TARGET ON APPROVAL_LOG (target_id, created_at DESC);
-- ===== END V10__raw_file_stage_and_approval_log.sql =====

-- ===== BEGIN V11__create_admin_user.sql =====
-- ADMIN_USER
CREATE TABLE ADMIN_USER (
    admin_id      NUMBER       NOT NULL,
    username      VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    status        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_USER PRIMARY KEY (admin_id),
    CONSTRAINT UK_ADMIN_USER_USERNAME UNIQUE (username)
);

CREATE SEQUENCE ADMIN_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ADMIN_USER_ROLE
CREATE TABLE ADMIN_USER_ROLE (
    role_id   NUMBER       NOT NULL,
    admin_id  NUMBER       NOT NULL,
    role_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_USER_ROLE PRIMARY KEY (role_id)
);

CREATE SEQUENCE ADMIN_USER_ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_ADMIN_USER_ROLE_ADMIN ON ADMIN_USER_ROLE (admin_id);

-- Default admin user (username: admin, password: admin1234)
-- NOTE: Uses "plain:" prefix for initial bootstrap. Change to BCrypt hash after setup.
INSERT INTO ADMIN_USER (admin_id, username, password_hash, status, created_at)
VALUES (ADMIN_USER_SEQ.NEXTVAL, 'admin', 'plain:admin1234', 'ACTIVE', SYSTIMESTAMP);

-- Roles for default admin
INSERT INTO ADMIN_USER_ROLE (role_id, admin_id, role_name, created_at)
VALUES (ADMIN_USER_ROLE_SEQ.NEXTVAL, (SELECT admin_id FROM ADMIN_USER WHERE username='admin'), 'SUPER_ADMIN', SYSTIMESTAMP);

INSERT INTO ADMIN_USER_ROLE (role_id, admin_id, role_name, created_at)
VALUES (ADMIN_USER_ROLE_SEQ.NEXTVAL, (SELECT admin_id FROM ADMIN_USER WHERE username='admin'), 'POLICY_WRITER', SYSTIMESTAMP);

INSERT INTO ADMIN_USER_ROLE (role_id, admin_id, role_name, created_at)
VALUES (ADMIN_USER_ROLE_SEQ.NEXTVAL, (SELECT admin_id FROM ADMIN_USER WHERE username='admin'), 'POLICY_APPROVER', SYSTIMESTAMP);
-- ===== END V11__create_admin_user.sql =====

-- ===== BEGIN V12__user_auth.sql =====
CREATE TABLE USER_AUTH (
    user_id       NUMBER       NOT NULL,
    username      VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT PK_USER_AUTH PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_AUTH_USERNAME UNIQUE (username)
);

CREATE SEQUENCE USER_AUTH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- ===== END V12__user_auth.sql =====

-- ===== BEGIN V13__user_credit_append_only.sql =====
-- USER_CREDIT_LV1 append-only
ALTER TABLE USER_CREDIT_LV1 ADD (
    lv1_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV1_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV1 SET lv1_id = USER_CREDIT_LV1_SEQ.NEXTVAL, is_active = 'Y' WHERE lv1_id IS NULL;
ALTER TABLE USER_CREDIT_LV1 MODIFY lv1_id NOT NULL;
ALTER TABLE USER_CREDIT_LV1 DROP CONSTRAINT PK_USER_CREDIT_LV1;
ALTER TABLE USER_CREDIT_LV1 ADD CONSTRAINT PK_USER_CREDIT_LV1 PRIMARY KEY (lv1_id);
CREATE INDEX IDX_UCLV1_USER_ACTIVE ON USER_CREDIT_LV1 (user_id, is_active, created_at DESC);

-- USER_CREDIT_LV2 append-only
ALTER TABLE USER_CREDIT_LV2 ADD (
    lv2_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV2_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV2 SET lv2_id = USER_CREDIT_LV2_SEQ.NEXTVAL, is_active = 'Y' WHERE lv2_id IS NULL;
ALTER TABLE USER_CREDIT_LV2 MODIFY lv2_id NOT NULL;
ALTER TABLE USER_CREDIT_LV2 DROP CONSTRAINT PK_USER_CREDIT_LV2;
ALTER TABLE USER_CREDIT_LV2 ADD CONSTRAINT PK_USER_CREDIT_LV2 PRIMARY KEY (lv2_id);
CREATE INDEX IDX_UCLV2_USER_ACTIVE ON USER_CREDIT_LV2 (user_id, is_active, created_at DESC);

-- USER_CREDIT_LV3 append-only
ALTER TABLE USER_CREDIT_LV3 ADD (
    lv3_id    NUMBER,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL
);
CREATE SEQUENCE USER_CREDIT_LV3_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
UPDATE USER_CREDIT_LV3 SET lv3_id = USER_CREDIT_LV3_SEQ.NEXTVAL, is_active = 'Y' WHERE lv3_id IS NULL;
ALTER TABLE USER_CREDIT_LV3 MODIFY lv3_id NOT NULL;
ALTER TABLE USER_CREDIT_LV3 DROP CONSTRAINT PK_USER_CREDIT_LV3;
ALTER TABLE USER_CREDIT_LV3 ADD CONSTRAINT PK_USER_CREDIT_LV3 PRIMARY KEY (lv3_id);
CREATE INDEX IDX_UCLV3_USER_ACTIVE ON USER_CREDIT_LV3 (user_id, is_active, created_at DESC);
-- ===== END V13__user_credit_append_only.sql =====

-- ===== BEGIN V14__recommend_history_explain_summary.sql =====
ALTER TABLE RECOMMEND_HISTORY ADD (
    explain_summary VARCHAR2(2000)
);
-- ===== END V14__recommend_history_explain_summary.sql =====

-- ===== BEGIN V15__raw_file_cell_normalized.sql =====
-- RAW_FILE_CELL (normalized key-value per row)
CREATE TABLE RAW_FILE_CELL (
    cell_id      NUMBER        NOT NULL,
    upload_id    NUMBER        NOT NULL,
    row_num      NUMBER        NOT NULL,
    column_name  VARCHAR2(200) NOT NULL,
    column_value VARCHAR2(4000),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_CELL PRIMARY KEY (cell_id)
);

CREATE SEQUENCE RAW_FILE_CELL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_RAW_FILE_CELL_UPLOAD ON RAW_FILE_CELL (upload_id, row_num);
-- ===== END V15__raw_file_cell_normalized.sql =====

-- ===== BEGIN V16__user_auth_status_lock.sql =====
ALTER TABLE USER_AUTH ADD (
    fail_login_count NUMBER DEFAULT 0 NOT NULL,
    is_locked        CHAR(1) DEFAULT 'N' NOT NULL,
    password_updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_AUTH ADD CONSTRAINT CK_USER_AUTH_LOCKED
    CHECK (is_locked IN ('Y','N'));

UPDATE USER_AUTH
   SET fail_login_count = 0
 WHERE fail_login_count IS NULL;

UPDATE USER_AUTH
   SET is_locked = 'N'
 WHERE is_locked IS NULL;
-- ===== END V16__user_auth_status_lock.sql =====

-- ===== BEGIN V17__recommend_history_reco_link.sql =====
ALTER TABLE RECOMMEND_HISTORY ADD (
    reco_request_id NUMBER,
    reco_result_id  NUMBER
);

CREATE INDEX IDX_RECOMMEND_HISTORY_RECO_RESULT
    ON RECOMMEND_HISTORY (reco_result_id);
-- ===== END V17__recommend_history_reco_link.sql =====

-- ===== BEGIN V18__eda_quality_code_normalize.sql =====
-- Normalized stage table
CREATE TABLE RAW_FILE_NORMALIZED (
    norm_id      NUMBER       NOT NULL,
    upload_id    NUMBER       NOT NULL,
    row_num      NUMBER       NOT NULL,
    column_name  VARCHAR2(200) NOT NULL,
    column_value VARCHAR2(4000),
    created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RAW_FILE_NORMALIZED PRIMARY KEY (norm_id)
);

CREATE SEQUENCE RAW_FILE_NORMALIZED_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_RAW_FILE_NORM_UPLOAD ON RAW_FILE_NORMALIZED (upload_id, row_num);

-- EDA tables
CREATE TABLE EDA_RUN (
    eda_run_id   NUMBER       NOT NULL,
    user_id      NUMBER,
    snapshot_id  NUMBER,
    version_id   NUMBER,
    created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EDA_RUN PRIMARY KEY (eda_run_id)
);

CREATE SEQUENCE EDA_RUN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE EDA_METRIC (
    metric_id         NUMBER       NOT NULL,
    eda_run_id        NUMBER       NOT NULL,
    metric_name       VARCHAR2(200),
    metric_type       VARCHAR2(100),
    metric_key        VARCHAR2(200),
    metric_value_path VARCHAR2(1000),
    created_at        TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EDA_METRIC PRIMARY KEY (metric_id)
);

CREATE SEQUENCE EDA_METRIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE EDA_STAT_RESULT (
    stat_id      NUMBER       NOT NULL,
    eda_run_id   NUMBER       NOT NULL,
    row_id       NUMBER,
    column_code  VARCHAR2(200),
    mean         NUMBER,
    median       NUMBER,
    std          NUMBER,
    min          NUMBER,
    max          NUMBER,
    q1           NUMBER,
    q3           NUMBER,
    skewness     NUMBER,
    kurtosis     NUMBER,
    missing_rate NUMBER,
    data_type    VARCHAR2(50),
    CONSTRAINT PK_EDA_STAT_RESULT PRIMARY KEY (stat_id)
);

CREATE SEQUENCE EDA_STAT_RESULT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE EDA_OUTLIER_RESULT (
    outlier_id   NUMBER       NOT NULL,
    eda_run_id   NUMBER       NOT NULL,
    row_id       NUMBER,
    column_code  VARCHAR2(200),
    method_code_value_id VARCHAR2(100),
    flag         CHAR(1),
    reason       VARCHAR2(1000),
    CONSTRAINT PK_EDA_OUTLIER_RESULT PRIMARY KEY (outlier_id)
);

CREATE SEQUENCE EDA_OUTLIER_RESULT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Quality issue
CREATE TABLE QUALITY_ISSUE (
    issue_id     NUMBER       NOT NULL,
    upload_id    NUMBER       NOT NULL,
    issue_type_code_value_id VARCHAR2(100),
    column_code  VARCHAR2(200),
    detail_json_path VARCHAR2(1000),
    status_code_value_id VARCHAR2(100),
    resolved_by_user_id NUMBER,
    resolved_at TIMESTAMP,
    detected_stage_code_value_id VARCHAR2(100),
    issued_at   TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QUALITY_ISSUE PRIMARY KEY (issue_id)
);

CREATE SEQUENCE QUALITY_ISSUE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Code set/value
CREATE TABLE CODE_SET (
    code_set_id   NUMBER       NOT NULL,
    code_set_key  VARCHAR2(100) NOT NULL,
    code_set_name VARCHAR2(200),
    description   VARCHAR2(1000),
    is_active     CHAR(1)       DEFAULT 'Y' NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CODE_SET PRIMARY KEY (code_set_id)
);

CREATE TABLE CODE_VALUE (
    code_value_id NUMBER       NOT NULL,
    code_set_id   NUMBER       NOT NULL,
    code          VARCHAR2(100) NOT NULL,
    code_name     VARCHAR2(200),
    sort_order    NUMBER,
    is_active     CHAR(1)       DEFAULT 'Y' NOT NULL,
    effective_from TIMESTAMP,
    effective_to  TIMESTAMP,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CODE_VALUE PRIMARY KEY (code_value_id)
);

CREATE SEQUENCE CODE_SET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CODE_VALUE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Seed minimal code sets/values
INSERT INTO CODE_SET (code_set_id, code_set_key, code_set_name, description, is_active)
VALUES (CODE_SET_SEQ.NEXTVAL, 'RAW_FILE_STATUS', 'Raw file status', 'Raw file pipeline statuses', 'Y');

INSERT INTO CODE_SET (code_set_id, code_set_key, code_set_name, description, is_active)
VALUES (CODE_SET_SEQ.NEXTVAL, 'QUALITY_ISSUE_TYPE', 'Quality issue type', 'Data quality issue types', 'Y');

INSERT INTO CODE_SET (code_set_id, code_set_key, code_set_name, description, is_active)
VALUES (CODE_SET_SEQ.NEXTVAL, 'QUALITY_STATUS', 'Quality status', 'Quality issue status', 'Y');

INSERT INTO CODE_SET (code_set_id, code_set_key, code_set_name, description, is_active)
VALUES (CODE_SET_SEQ.NEXTVAL, 'DETECTED_STAGE', 'Detected stage', 'Detection stage', 'Y');

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'UPLOADED', 'Uploaded', 1, 'Y'
  FROM CODE_SET WHERE code_set_key = 'RAW_FILE_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'VALIDATED', 'Validated', 2, 'Y'
  FROM CODE_SET WHERE code_set_key = 'RAW_FILE_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'FAILED', 'Failed', 3, 'Y'
  FROM CODE_SET WHERE code_set_key = 'RAW_FILE_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'INGESTED', 'Ingested', 4, 'Y'
  FROM CODE_SET WHERE code_set_key = 'RAW_FILE_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'NORMALIZED', 'Normalized', 5, 'Y'
  FROM CODE_SET WHERE code_set_key = 'RAW_FILE_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'MISSING_RATE', 'Missing rate', 1, 'Y'
  FROM CODE_SET WHERE code_set_key = 'QUALITY_ISSUE_TYPE';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'OPEN', 'Open', 1, 'Y'
  FROM CODE_SET WHERE code_set_key = 'QUALITY_STATUS';

INSERT INTO CODE_VALUE (code_value_id, code_set_id, code, code_name, sort_order, is_active)
SELECT CODE_VALUE_SEQ.NEXTVAL, code_set_id, 'EDA', 'EDA', 1, 'Y'
  FROM CODE_SET WHERE code_set_key = 'DETECTED_STAGE';
-- ===== END V18__eda_quality_code_normalize.sql =====

-- ===== BEGIN V19__policy_deploy_history_audit_ext.sql =====
-- Policy deploy history
CREATE TABLE POLICY_DEPLOY_LOG (
    deploy_id          NUMBER       NOT NULL,
    policy_id          NUMBER       NOT NULL,
    previous_policy_id NUMBER,
    action             VARCHAR2(20) NOT NULL, -- DEPLOY / ROLLBACK
    reason             VARCHAR2(1000),
    actor_id           VARCHAR2(100),
    deployed_at        TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POLICY_DEPLOY_LOG PRIMARY KEY (deploy_id)
);

CREATE SEQUENCE POLICY_DEPLOY_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_POLICY_DEPLOY_LOG_POLICY
    ON POLICY_DEPLOY_LOG (policy_id, deployed_at DESC);

-- Audit log expansion
ALTER TABLE AUDIT_LOG ADD (
    actor_roles VARCHAR2(400),
    detail_json CLOB
);
-- ===== END V19__policy_deploy_history_audit_ext.sql =====

-- ===== BEGIN V20__product_rate_tables.sql =====
-- PRODUCT_INTEREST_RATE: 상품 금리(기본)
CREATE TABLE PRODUCT_INTEREST_RATE (
    rate_id     NUMBER          NOT NULL,
    product_id  NUMBER          NOT NULL,
    rate_base   NUMBER,
    rate_min    NUMBER,
    rate_max    NUMBER,
    as_of_date  DATE            NOT NULL,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PRODUCT_INTEREST_RATE PRIMARY KEY (rate_id)
);

CREATE SEQUENCE PRODUCT_INTEREST_RATE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_PROD_INT_RATE_PRODUCT
    ON PRODUCT_INTEREST_RATE (product_id, as_of_date DESC);

-- PRODUCT_RATE_SNAPSHOT: 사용자/시점 기준 금리 스냅샷
CREATE TABLE PRODUCT_RATE_SNAPSHOT (
    rate_id     NUMBER          NOT NULL,
    product_id  NUMBER          NOT NULL,
    rate_min    NUMBER,
    rate_max    NUMBER,
    score_base  NUMBER,
    rate_type   VARCHAR2(50),
    as_of_date  DATE            NOT NULL,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PRODUCT_RATE_SNAPSHOT PRIMARY KEY (rate_id)
);

CREATE SEQUENCE PRODUCT_RATE_SNAPSHOT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_PROD_RATE_SNAPSHOT_PRODUCT
    ON PRODUCT_RATE_SNAPSHOT (product_id, as_of_date DESC);
-- ===== END V20__product_rate_tables.sql =====

-- ===== BEGIN V21__add_provider_and_external_keys.sql =====
-- PROVIDER: 금융회사
CREATE TABLE PROVIDER (
    provider_id   NUMBER          NOT NULL,
    fin_co_no     VARCHAR2(20)    NOT NULL,
    company_name  VARCHAR2(200)   NOT NULL,
    created_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (provider_id),
    CONSTRAINT UQ_PROVIDER_FIN_CO_NO UNIQUE (fin_co_no)
);

CREATE SEQUENCE PROVIDER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_PROVIDER_NAME
    ON PROVIDER (company_name);

-- LOAN_PRODUCT: FSS 외부 키/표시정보 추가
ALTER TABLE LOAN_PRODUCT ADD (
    fin_prdt_cd   VARCHAR2(50),
    fin_co_no     VARCHAR2(20),
    company_name  VARCHAR2(200),
    join_way      VARCHAR2(200),
    cb_name       VARCHAR2(100)
);

CREATE INDEX IDX_LOAN_PRODUCT_FSS_KEY
    ON LOAN_PRODUCT (fin_co_no, fin_prdt_cd);

ALTER TABLE LOAN_PRODUCT
    ADD CONSTRAINT UQ_LOAN_PRODUCT_FSS UNIQUE (fin_co_no, fin_prdt_cd);
-- ===== END V21__add_provider_and_external_keys.sql =====

-- ===== BEGIN V22__user_auth_login_failures.sql =====
CREATE INDEX IDX_USER_AUTH_STATUS ON USER_AUTH (status, is_locked);
-- ===== END V22__user_auth_login_failures.sql =====

-- ===== BEGIN V23__provider_url.sql =====
-- PROVIDER_URL: 금융사 홈페이지 URL 매핑
CREATE TABLE PROVIDER_URL (
    fin_co_no     VARCHAR2(20) PRIMARY KEY,
    homepage_url  VARCHAR2(500) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_PROVIDER_URL_HOME ON PROVIDER_URL (homepage_url);
-- ===== END V23__provider_url.sql =====
