-- =========================================================
-- V2: 기관/상품 + 메타 사전 (PROVIDER/PRODUCT/* + CODE_DICTIONARY*)
-- (V1의 CATEGORY_*, USER_PROFILE, RAW_FILE_UPLOAD가 선행되어야 함)
-- =========================================================

-- 4) PROVIDER
CREATE TABLE PROVIDER (
  provider_id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name                   VARCHAR2(300) NOT NULL,
  provider_type_category_value_id NUMBER NOT NULL,
  source_group_category_value_id  NUMBER NOT NULL
);

ALTER TABLE PROVIDER
  ADD CONSTRAINT FK_PROVIDER_TYPE
  FOREIGN KEY (provider_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE PROVIDER
  ADD CONSTRAINT FK_PROVIDER_SOURCE_GROUP
  FOREIGN KEY (source_group_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장
CREATE INDEX IX_PROVIDER_TYPE        ON PROVIDER(provider_type_category_value_id);
CREATE INDEX IX_PROVIDER_SOURCE_GRP  ON PROVIDER(source_group_category_value_id);

-- (선택) 기관명이 유니크여야 하면 유니크 인덱스 권장
-- CREATE UNIQUE INDEX UX_PROVIDER_NAME ON PROVIDER(provider_name);


-- 5) PRODUCT
CREATE TABLE PRODUCT (
  product_id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id                      NUMBER NOT NULL,
  product_name                     VARCHAR2(500) NOT NULL,
  product_type_category_value_id   NUMBER NOT NULL,
  loan_type_category_value_id      NUMBER NOT NULL,
  repayment_type_category_value_id NUMBER NOT NULL,
  collateral_type_category_value_id NUMBER NOT NULL,
  rate_type_category_value_id      NUMBER NOT NULL,
  note                             VARCHAR2(1000),
  add_date                         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  end_date                         DATE,
  CONSTRAINT CK_PRODUCT_END_DATE CHECK (end_date IS NULL OR end_date >= TRUNC(add_date))
);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_PROVIDER
  FOREIGN KEY (provider_id) REFERENCES PROVIDER(provider_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_PRODUCT_TYPE
  FOREIGN KEY (product_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_LOAN_TYPE
  FOREIGN KEY (loan_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_REPAYMENT_TYPE
  FOREIGN KEY (repayment_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_COLLATERAL_TYPE
  FOREIGN KEY (collateral_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_RATE_TYPE
  FOREIGN KEY (rate_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장
CREATE INDEX IX_PRODUCT_PROVIDER        ON PRODUCT(provider_id);
CREATE INDEX IX_PRODUCT_PRODUCT_TYPE    ON PRODUCT(product_type_category_value_id);
CREATE INDEX IX_PRODUCT_LOAN_TYPE       ON PRODUCT(loan_type_category_value_id);
CREATE INDEX IX_PRODUCT_REPAYMENT_TYPE  ON PRODUCT(repayment_type_category_value_id);
CREATE INDEX IX_PRODUCT_COLLATERAL_TYPE ON PRODUCT(collateral_type_category_value_id);
CREATE INDEX IX_PRODUCT_RATE_TYPE       ON PRODUCT(rate_type_category_value_id);

-- (선택) 기관 내 상품명이 유니크여야 하면
-- CREATE UNIQUE INDEX UX_PRODUCT_PROVIDER_NAME ON PRODUCT(provider_id, product_name);


-- 6) PRODUCT_INTEREST_RATE
CREATE TABLE PRODUCT_INTEREST_RATE (
  rate_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  NUMBER NOT NULL,
  rate_base   NUMBER,
  rate_min    NUMBER,
  rate_max    NUMBER,
  as_of_date  DATE NOT NULL,
  CONSTRAINT CK_PIR_RATE_RANGE CHECK (
    (rate_min IS NULL OR rate_max IS NULL OR rate_min <= rate_max)
    AND (rate_base IS NULL OR rate_min IS NULL OR rate_base >= rate_min)
    AND (rate_base IS NULL OR rate_max IS NULL OR rate_base <= rate_max)
  )
);

ALTER TABLE PRODUCT_INTEREST_RATE
  ADD CONSTRAINT FK_PRODUCT_INTEREST_RATE_PRODUCT
  FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id);

-- FK 인덱스 + (중복 방지) 유니크 권장
CREATE INDEX IX_PIR_PRODUCT ON PRODUCT_INTEREST_RATE(product_id);
CREATE UNIQUE INDEX UX_PIR_PRODUCT_ASOF ON PRODUCT_INTEREST_RATE(product_id, as_of_date);


-- 7) PRODUCT_RATE_SNAPSHOT
CREATE TABLE PRODUCT_RATE_SNAPSHOT (
  rate_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  NUMBER NOT NULL,
  rate_min    NUMBER,
  rate_max    NUMBER,
  score_base  NUMBER,
  as_of_date  DATE NOT NULL,
  rate_type   VARCHAR2(100),
  CONSTRAINT CK_PRS_RATE_RANGE CHECK (
    rate_min IS NULL OR rate_max IS NULL OR rate_min <= rate_max
  )
);

ALTER TABLE PRODUCT_RATE_SNAPSHOT
  ADD CONSTRAINT FK_PRODUCT_RATE_SNAPSHOT_PRODUCT
  FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id);

-- FK 인덱스 + (스냅샷 중복 방지) 유니크 권장
CREATE INDEX IX_PRS_PRODUCT ON PRODUCT_RATE_SNAPSHOT(product_id);
CREATE UNIQUE INDEX UX_PRS_PRODUCT_ASOF_TYPE ON PRODUCT_RATE_SNAPSHOT(product_id, as_of_date, rate_type);


-- 8) PRODUCT_ELIGIBILITY
CREATE TABLE PRODUCT_ELIGIBILITY (
  product_id        NUMBER PRIMARY KEY,
  min_age           NUMBER,
  max_age           NUMBER,
  min_income        NUMBER,
  max_dti           NUMBER,
  min_credit_score  NUMBER,
  max_dsr           NUMBER,
  employment_type   VARCHAR2(100),
  CONSTRAINT CK_PE_AGE CHECK (min_age IS NULL OR max_age IS NULL OR min_age <= max_age),
  CONSTRAINT CK_PE_NUM CHECK (
    (min_income IS NULL OR min_income >= 0)
    AND (max_dti IS NULL OR max_dti >= 0)
    AND (max_dsr IS NULL OR max_dsr >= 0)
    AND (min_credit_score IS NULL OR min_credit_score >= 0)
  )
);

ALTER TABLE PRODUCT_ELIGIBILITY
  ADD CONSTRAINT FK_PRODUCT_ELIGIBILITY_PRODUCT
  FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id);


-- 9) CODE_DICTIONARY_VERSION
CREATE TABLE CODE_DICTIONARY_VERSION (
  version_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upload_id      NUMBER NOT NULL,
  version_label  VARCHAR2(200) NOT NULL,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE CODE_DICTIONARY_VERSION
  ADD CONSTRAINT FK_CODE_DICT_VERSION_UPLOAD
  FOREIGN KEY (upload_id) REFERENCES RAW_FILE_UPLOAD(upload_id);

-- FK 인덱스 권장
CREATE INDEX IX_CODE_DICT_VER_UPLOAD ON CODE_DICTIONARY_VERSION(upload_id);

-- (선택) 버전 라벨이 업로드 내 유니크라면
-- CREATE UNIQUE INDEX UX_CODE_DICT_VER_UPLOAD_LABEL ON CODE_DICTIONARY_VERSION(upload_id, version_label);


-- 10) CODE_DICTIONARY
CREATE TABLE CODE_DICTIONARY (
  dict_id                           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id                        NUMBER NOT NULL,
  column_code                       VARCHAR2(200) NOT NULL,
  column_name                       VARCHAR2(300),
  column_desc                       VARCHAR2(2000),
  large_category_category_value_id  NUMBER,
  mideum_category_category_value_id NUMBER, -- ※ 오탈자 가능( medium )이지만, 기존 사용중이면 변경 금지
  small_category_category_value_id  NUMBER,
  is_required                       CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT CK_CODE_DICT_REQUIRED CHECK (is_required IN ('Y','N'))
);

CREATE INDEX IX_CODE_DICT_VERSION ON CODE_DICTIONARY(version_id);
CREATE UNIQUE INDEX UX_CODE_DICT_VERSION_COL ON CODE_DICTIONARY(version_id, column_code);

ALTER TABLE CODE_DICTIONARY
  ADD CONSTRAINT FK_CODE_DICT_VERSION
  FOREIGN KEY (version_id) REFERENCES CODE_DICTIONARY_VERSION(version_id);

ALTER TABLE CODE_DICTIONARY
  ADD CONSTRAINT FK_CODE_DICT_LARGE_CAT
  FOREIGN KEY (large_category_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE CODE_DICTIONARY
  ADD CONSTRAINT FK_CODE_DICT_MID_CAT
  FOREIGN KEY (mideum_category_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

ALTER TABLE CODE_DICTIONARY
  ADD CONSTRAINT FK_CODE_DICT_SMALL_CAT
  FOREIGN KEY (small_category_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장(카테고리로 검색/조인 시)
CREATE INDEX IX_CODE_DICT_LARGE_CAT ON CODE_DICTIONARY(large_category_category_value_id);
CREATE INDEX IX_CODE_DICT_MID_CAT   ON CODE_DICTIONARY(mideum_category_category_value_id);
CREATE INDEX IX_CODE_DICT_SMALL_CAT ON CODE_DICTIONARY(small_category_category_value_id);


-- 11) CODE_DICTIONARY_DIFF
CREATE TABLE CODE_DICTIONARY_DIFF (
  diff_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pre_version_id   NUMBER NOT NULL,
  post_version_id  NUMBER NOT NULL,
  change_type      VARCHAR2(20) NOT NULL, -- ADD/MOD/DEL
  column_code      VARCHAR2(200) NOT NULL,
  before_json_path VARCHAR2(1000),
  after_json_path  VARCHAR2(1000),
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_CODE_DICT_DIFF_TYPE CHECK (change_type IN ('ADD','MOD','DEL')),
  CONSTRAINT CK_CODE_DICT_DIFF_VER  CHECK (pre_version_id <> post_version_id)
);

ALTER TABLE CODE_DICTIONARY_DIFF
  ADD CONSTRAINT FK_CODE_DICT_DIFF_PRE
  FOREIGN KEY (pre_version_id) REFERENCES CODE_DICTIONARY_VERSION(version_id);

ALTER TABLE CODE_DICTIONARY_DIFF
  ADD CONSTRAINT FK_CODE_DICT_DIFF_POST
  FOREIGN KEY (post_version_id) REFERENCES CODE_DICTIONARY_VERSION(version_id);

-- FK 인덱스 권장
CREATE INDEX IX_CODE_DICT_DIFF_PRE  ON CODE_DICTIONARY_DIFF(pre_version_id);
CREATE INDEX IX_CODE_DICT_DIFF_POST ON CODE_DICTIONARY_DIFF(post_version_id);


-- 33) INDICATOR_DEFINITION (지표 정의)
CREATE TABLE INDICATOR_DEFINITION (
  indicator_code  VARCHAR2(200) PRIMARY KEY,
  formula_text    VARCHAR2(2000),
  description     VARCHAR2(2000)
);
