-- =========================================================
-- V3: 동의/신용/LV/스냅샷/리스크
-- (V1 USER_PROFILE, V2 CODE_DICTIONARY_VERSION 등이 선행되어야 함)
-- =========================================================

-- 19) USER_CONSENT
CREATE TABLE USER_CONSENT (
  consent_id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                        NUMBER NOT NULL,
  consent_type_category_value_id NUMBER NOT NULL,
  agreed_yn                      CHAR(1) DEFAULT 'N' NOT NULL,
  agreed_at                      TIMESTAMP,
  expired_at                     TIMESTAMP,
  CONSTRAINT CK_USER_CONSENT_AGREED CHECK (agreed_yn IN ('Y','N')),
  CONSTRAINT CK_USER_CONSENT_TIME CHECK (agreed_at IS NULL OR expired_at IS NULL OR agreed_at <= expired_at)
);

ALTER TABLE USER_CONSENT
  ADD CONSTRAINT FK_USER_CONSENT_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

ALTER TABLE USER_CONSENT
  ADD CONSTRAINT FK_USER_CONSENT_TYPE
  FOREIGN KEY (consent_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장
CREATE INDEX IX_USER_CONSENT_USER ON USER_CONSENT(user_id);
CREATE INDEX IX_USER_CONSENT_TYPE ON USER_CONSENT(consent_type_category_value_id);

-- (선택) 유저+동의유형 중복 방지(동의 이력을 1건만 유지할 때)
-- CREATE UNIQUE INDEX UX_USER_CONSENT_USER_TYPE ON USER_CONSENT(user_id, consent_type_category_value_id);


-- 20) USER_INPUT_HISTORY
CREATE TABLE USER_INPUT_HISTORY (
  history_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                     NUMBER NOT NULL,
  input_type_category_value_id NUMBER NOT NULL,
  input_json_path             VARCHAR2(1000),
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_INPUT_HISTORY
  ADD CONSTRAINT FK_USER_INPUT_HISTORY_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);

ALTER TABLE USER_INPUT_HISTORY
  ADD CONSTRAINT FK_USER_INPUT_HISTORY_TYPE
  FOREIGN KEY (input_type_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장
CREATE INDEX IX_USER_INPUT_HISTORY_USER ON USER_INPUT_HISTORY(user_id);
CREATE INDEX IX_USER_INPUT_HISTORY_TYPE ON USER_INPUT_HISTORY(input_type_category_value_id);


-- 21) USER_CREDIT_LV1
CREATE TABLE USER_CREDIT_LV1 (
  user_id      NUMBER PRIMARY KEY,
  age          NUMBER,
  income_year  NUMBER,
  gender       VARCHAR2(20),
  CONSTRAINT CK_USER_CREDIT_LV1_AGE CHECK (age IS NULL OR age >= 0),
  CONSTRAINT CK_USER_CREDIT_LV1_INCOME CHECK (income_year IS NULL OR income_year >= 0)
);

ALTER TABLE USER_CREDIT_LV1
  ADD CONSTRAINT FK_USER_CREDIT_LV1_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 22) USER_CREDIT_LV2
CREATE TABLE USER_CREDIT_LV2 (
  user_id           NUMBER PRIMARY KEY,
  employment_type   VARCHAR2(100),
  residence_type    VARCHAR2(100),
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_CREDIT_LV2
  ADD CONSTRAINT FK_USER_CREDIT_LV2_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 23) USER_CREDIT_LV3
CREATE TABLE USER_CREDIT_LV3 (
  user_id              NUMBER PRIMARY KEY,
  loan_purpose         VARCHAR2(200),
  total_debt           NUMBER,
  existing_loan_count  NUMBER,
  CONSTRAINT CK_USER_CREDIT_LV3_DEBT CHECK (total_debt IS NULL OR total_debt >= 0),
  CONSTRAINT CK_USER_CREDIT_LV3_COUNT CHECK (existing_loan_count IS NULL OR existing_loan_count >= 0)
);

ALTER TABLE USER_CREDIT_LV3
  ADD CONSTRAINT FK_USER_CREDIT_LV3_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 24) USER_CREDIT_SNAPSHOT
CREATE TABLE USER_CREDIT_SNAPSHOT (
  snapshot_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          NUMBER NOT NULL,
  monthly_payment  NUMBER,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_USER_CREDIT_SNAPSHOT_PAY CHECK (monthly_payment IS NULL OR monthly_payment >= 0)
);

-- 이미 인덱스가 있으니 OK (FK 성능/락 완화)
CREATE INDEX IX_USER_CREDIT_SNAPSHOT_USER ON USER_CREDIT_SNAPSHOT(user_id);

ALTER TABLE USER_CREDIT_SNAPSHOT
  ADD CONSTRAINT FK_USER_CREDIT_SNAPSHOT_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 25) CARD_ACTIVITY_METRIC
CREATE TABLE CARD_ACTIVITY_METRIC (
  snapshot_id    NUMBER PRIMARY KEY,
  issued_count   NUMBER,
  active_count   NUMBER,
  density_score  NUMBER,
  activity_score NUMBER,
  CONSTRAINT CK_CARD_ACTIVITY_CNT CHECK (
    (issued_count IS NULL OR issued_count >= 0)
    AND (active_count IS NULL OR active_count >= 0)
  )
);

ALTER TABLE CARD_ACTIVITY_METRIC
  ADD CONSTRAINT FK_CARD_ACTIVITY_METRIC_SNAPSHOT
  FOREIGN KEY (snapshot_id) REFERENCES USER_CREDIT_SNAPSHOT(snapshot_id);


-- 26) USER_DEBT_DETAIL
CREATE TABLE USER_DEBT_DETAIL (
  debt_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          NUMBER NOT NULL,
  debt_type        VARCHAR2(100),
  balance          NUMBER,
  monthly_payment  NUMBER,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_USER_DEBT_DETAIL_NUM CHECK (
    (balance IS NULL OR balance >= 0)
    AND (monthly_payment IS NULL OR monthly_payment >= 0)
  )
);

CREATE INDEX IX_USER_DEBT_DETAIL_USER ON USER_DEBT_DETAIL(user_id);

ALTER TABLE USER_DEBT_DETAIL
  ADD CONSTRAINT FK_USER_DEBT_DETAIL_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 27) USER_RISK_DETAIL
CREATE TABLE USER_RISK_DETAIL (
  risk_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          NUMBER NOT NULL,
  credit_score     NUMBER,
  dti              NUMBER,
  dsr              NUMBER,
  repayment_cap    NUMBER,
  stability_score  NUMBER,
  normalized_soc   VARCHAR2(1000), -- JSON "본문"이 아니라 "경로"라면 path 컬럼명으로 바꾸는 게 더 명확합니다.
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_USER_RISK_DETAIL_NUM CHECK (
    (credit_score IS NULL OR credit_score >= 0)
    AND (dti IS NULL OR dti >= 0)
    AND (dsr IS NULL OR dsr >= 0)
    AND (repayment_cap IS NULL OR repayment_cap >= 0)
  )
);

CREATE INDEX IX_USER_RISK_DETAIL_USER ON USER_RISK_DETAIL(user_id);

ALTER TABLE USER_RISK_DETAIL
  ADD CONSTRAINT FK_USER_RISK_DETAIL_USER
  FOREIGN KEY (user_id) REFERENCES USER_PROFILE(user_id);


-- 28) CREDIT_RISK_SCORE
CREATE TABLE CREDIT_RISK_SCORE (
  snapshot_id                 NUMBER PRIMARY KEY,
  risk_score                  NUMBER,
  risk_summary                NUMBER,
  risk_flag_category_value_id NUMBER,
  components_json_path        VARCHAR2(1000),
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_CREDIT_RISK_SCORE_NUM CHECK (
    (risk_score IS NULL OR risk_score >= 0)
    AND (risk_summary IS NULL OR risk_summary >= 0)
  )
);

ALTER TABLE CREDIT_RISK_SCORE
  ADD CONSTRAINT FK_CREDIT_RISK_SCORE_SNAPSHOT
  FOREIGN KEY (snapshot_id) REFERENCES USER_CREDIT_SNAPSHOT(snapshot_id);

ALTER TABLE CREDIT_RISK_SCORE
  ADD CONSTRAINT FK_CREDIT_RISK_SCORE_FLAG
  FOREIGN KEY (risk_flag_category_value_id) REFERENCES CATEGORY_VALUE(category_value_id);

-- FK 인덱스 권장(특히 FLAG로 필터링/집계하면 효과 큼)
CREATE INDEX IX_CREDIT_RISK_SCORE_FLAG ON CREDIT_RISK_SCORE(risk_flag_category_value_id);

-- ❌ 아래는 컬럼명이 맞지 않아 실패 + "path"에 JSON 체크도 부적합하므로 제거
-- ALTER TABLE CREDIT_RISK_SCORE
--   ADD CONSTRAINT CK_CREDIT_RISK_SCORE_JSON CHECK (components_json IS JSON);
