-- 승인/활성 버전 컬럼 추가 (CODE_DICTIONARY_VERSION, RECO_POLICY)
-- 설계서 기준 승인/활성 분리 적용

ALTER TABLE CODE_DICTIONARY_VERSION ADD (
    status      VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR2(100),
    is_active   CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE RECO_POLICY ADD (
    status      VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR2(100),
    is_active   CHAR(1) DEFAULT 'N' NOT NULL
);

-- 상태 체크 제약
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_STATUS
    CHECK (status IN ('DRAFT','APPROVED','DEPRECATED'));

-- 활성 플래그 체크 제약
ALTER TABLE CODE_DICTIONARY_VERSION ADD CONSTRAINT CK_CODE_DICT_ACTIVE
    CHECK (is_active IN ('Y','N'));

ALTER TABLE RECO_POLICY ADD CONSTRAINT CK_RECO_POLICY_ACTIVE
    CHECK (is_active IN ('Y','N'));

-- 조회 인덱스
CREATE INDEX IDX_CODE_DICT_ACTIVE ON CODE_DICTIONARY_VERSION (is_active, status, approved_at DESC);
CREATE INDEX IDX_RECO_POLICY_ACTIVE ON RECO_POLICY (is_active, status, approved_at DESC);
